### ISSUE TITLE
???

### ISSUE THREAD

**Issue by op183** [slovensko-help/data-korona#2]
Počet pozitívne testovaných pacientov PCR testami === 282 864  https://covid-19.nczisk.sk/sk 17/02/2021

Počet potvrdených PCR testami  === 514524 https://korona.gov.sk/koronavirus-na-slovensku-v-cislach/

Je jasné, že pracujete pod tlakom, ale takéto chyby sú neodpustitelné.

**Comment by filiplikavcan** [comment]
Dakujeme za upozornenie. Bola tam zla popiska. Ten udaj vyjadroval pocet potvrdenych PCR+AG. Je to v grafe opravene tak, ze uz sa zobrazuje len pocet potvrdenych PCR.
